### ISSUE TITLE
Corepack runs into an internal error with node version node:iron@sha256:04223c46b1b8998bccbb6e6208dbed8344916ffc1be9f446109ffcb9629ad791

### ISSUE THREAD

**Issue by Chreggii** [nodejs/corepack#447]
When I try to install pnpm with corepack I get the following error with the node version node:iron@sha256:04223c46b1b8998bccbb6e6208dbed8344916ffc1be9f446109ffcb9629ad791:

`$ npm config set //$CI_SERVER_HOST/:_authToken $CI_JOB_TOKEN
$ https_proxy=$CODE_PROXY corepack prepare --activate && corepack enable
Preparing pnpm@8.15.6 for immediate activation...
Internal Error: Error when performing the request to https://registry.npmjs.org/pnpm/-/pnpm-8.15.6.tgz; for troubleshooting help, see https://github.com/nodejs/corepack#troubleshooting
    at fetch (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:22882:11)
    at async fetchUrlStream (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:2[29](https://code.siemens.com/automation-core/ac-engineering/-/jobs/174743095#L29)14:20)
    at async installVersion (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:2[30](https://code.siemens.com/automation-core/ac-engineering/-/jobs/174743095#L30)84:18)
    at async Engine.ensurePackageManager (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:23380:32)
    at async PrepareCommand.execute (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:24147:27)
    at async PrepareCommand.validateAndExecute (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21173:22)
    at async _Cli.run (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:22148:18)
    at async Object.runMain (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:24266:12)`

**Comment by Chreggii** [comment]
It seems to be an issue with the proxy. 

For reproducing the issue run the following code in a gitlab-ci pipeline (new node image):

```
stages:
  - build

build:
  stage: build
  image: node:iron@sha256:b73550fae550a1385e56500f4d95545f4808439828786e9bff9913e6a57989dc
  before_script:
    - corepack enable
    - HTTPS_PROXY=$CODE_PROXY corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - HTTPS_PROXY=$CODE_PROXY pnpm install # install dependencies
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
```
    
With the previous node image everything worked fine:
```
stages:
  - build

build:
  stage: build
  image: node:iron@sha256:894c91653e564b9ba29400e6e1675bbcbc667158c1706c655dd4ccf84d0f54e8
  before_script:
    - corepack enable
    - HTTPS_PROXY=$CODE_PROXY corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - HTTPS_PROXY=$CODE_PROXY pnpm install # install dependencies
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
```
